server:
  port: 8082

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017

logging:
  level:
    org:
      springframework:
        web: warn
        security: warn
    online.lokals.lokalapi.game:
      backgammon: warn
      pishti: warn

jwt:
  secret: ${JWT_SECRET:parolaisaret}
  validityInDays: ${JWT_VALIDITY:365}
