jwt:
  secret: lokalsecret_dev
  validityInDays: 365


logging:
  level:
    org:
      springframework:
        web: warn
        security: warn
    online.lokals.lokalapi.game:
      backgammon: trace
      pishti: trace