jwt:
#  private.key: classpath:private.pem
#  public.key: classpath:public.pem
  secret: lokalsecret_dev
  validityInDays: 365


logging:
  level:
    org:
      springframework:
        web: debug
        security: trace