spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017

jwt:
  secret: parolaisaret
  validityInDays: 365

logging:
  level:
    org:
      springframework:
        web: warn
        security: warn
    online.lokals.lokalapi.game:
      backgammon: warn
      pishti: warn
      batak: trace